spring.application.name=interview-helper
spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration
ai.server.base-url=${AI_SERVER_BASE_URL:http://13.125.255.148:8000}
